# URLs
BINANCE_REST_URL = 'https://api.binance.com/api/v3/depth'
BINANCE_WEBSOCKET_URL = 'wss://stream.binance.com:9443/ws/{0}@depth'
# Envirnoment Variables
ENV_VAR_SYMBOL = 'SYMBOL'
ENV_VAR_PRICE_RESOLUTION = 'PRICE_RESOLUTION'
ENV_VAR_TIME_RESOLUTION_IN_SECONDS = 'TIME_RESOLUTION_IN_SECONDS'
ENV_VAR_LEVELS_PER_SIDE = 'LEVELS_PER_SIDE'
ENV_VAR_STORAGE_BATCH_SIZE = 'STORAGE_BATCH_SIZE'
ENV_VAR_CSV_STORAGE_DIRECTORY = 'CSV_STORAGE_DIRECTORY'